### ISSUE TITLE
issue with react-app

### ISSUE THREAD

**Issue by joshua1** [kriasoft/react-app#28]
I installed react-app globally, then in an empty folder ran ```react-app new```. 
then got the below 
```
Scaffolding a new JavaScript application in /Users/admin/Documents/Development_Stuff/B/ra
Installing 'react-app-tools' from npm... This may take a couple minutes.

> fsevents@1.1.3 install /Users/admin/Documents/Development_Stuff/B/ra/node_modules/fsevents
> node install

[fsevents] Success: "/Users/admin/Documents/Development_Stuff/B/ra/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/admin/Documents/Development_Stuff/B/ra/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @babel/plugin-syntax-dynamic-import@7.0.0-beta.34 requires a peer of @babel/core@7.0.0-beta.34 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ra No description
npm WARN ra No repository field.
npm WARN ra No license field.

+ react-app-tools@2.0.1
added 1758 packages from 885 contributors in 76.217s
Error: Cannot find module '/Users/admin/Documents/Development_Stuff/B/ra/node_modules/react-app-tools/scripts/new'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Promise.resolve.then.then.then (/Users/admin/.config/yarn/global/node_modules/react-app/cli.js:107:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by koistya** [comment]
@joshua1 you can bootstrap a new empty project by running:

```bash
$ yarn create react-app --scripts-version react-app-tools@2.0.2 hello-world
$ cd ./hello-world
$ yarn start
```

Just replace `hello-world` with the name of your project. Alternatively, you can start from this boilerplate that has core web application building blocks in place (authentication, GraphQL API endpoint, etc.):

```bash
$ git clone -o react-firebase-starter https://github.com/kriasoft/react-firebase-starter.git hello-world
$ cd ./hello-world
$ yarn setup
$ yarn start
```
